plugins {
    // MC 26.1+ usa el nuevo loom que NO remapea (el juego ya trae los nombres
    // oficiales de Mojang). Por eso no hay línea 'mappings' ni 'modImplementation'.
    id 'net.fabricmc.fabric-loom' version '1.16-SNAPSHOT'
}

version = '2.1.0'
group   = 'com.example'

base {
    archivesName = 'double-chest-esp'
}

repositories {
    mavenCentral()
    maven { url 'https://maven.fabricmc.net/' }
    maven { url 'https://maven.meteordev.org/releases' }
    maven { url 'https://maven.meteordev.org/snapshots' }
}

dependencies {
    minecraft      'com.mojang:minecraft:26.1.2'
    implementation 'net.fabricmc:fabric-loader:0.19.2'

    // Meteor Client snapshot para MC 26.1.2
    implementation 'meteordevelopment:meteor-client:26.1.2-SNAPSHOT'
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

java {
    // 26.1.2 requiere JDK 25 (java-runtime-epsilon).
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}
